#开发环境(写代码)
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 960812
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #日志配置
  logging:
    level:          #日志级别
      root: info     #springboot默认的级别
      com.cwb: debug
    file: log/blog-dev.log