#生产环境(上线)
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 960812
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


  #日志配置
  logging:
    level:            #日志级别
      root: warn      #springboot默认的级别
      com.cwb: info
    file: log/blog-pro.log


  server:
    port: 8081